<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;NU1902;NU1903</NoWarn>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    <NeutralLanguage>en</NeutralLanguage>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Tests'))">
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707;CA1861;xUnit1030</NoWarn>
  </PropertyGroup>
</Project>
